version: "3"
services:
    rstats:
        image: gcr.io/kaggle-images/rstats:staging 
        container_name: rstats
        volumes:
            - $PWD:/home/rstudio/project
        working_dir: /home/rstudio
        tty: true
        ports:
            - 8787:8787