---
title: 'Event Studies'
author: 'Takuma Kinoshita'
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(broom)
library(sf)
library(rgdal)
library(lme4)
library(rstan)
library(brms)
library(bayesplot)
library(zoo)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

## Load Data

```{r}
setwd("/Users/takuma/Documents/30_pp205_apa/3_project")

islands <- c('東京大島', '新島', '神津島', '小笠原', '八丈', '東京三宅')
metro_areas <- c("千代田", "中央", "港", "新宿", "文京", "台東", "墨田",
                 "江東", "品川", "目黒", "大田", "世田谷", "渋谷", "中野",
                 "杉並", "豊島", "北", "荒川", "板橋", "練馬", "足立", "葛飾", "江戸川")

data <- read_sf('data/input/prices_and_maps_tokyo.geojson', as_tibble = TRUE) %>%
    filter(!city %in% islands) %>%  # remove islands
    filter(city %in% metro_areas) %>%  # remove subverb area
    filter(duplicate_no == 0)  # left only first map if multiples
plot(data, max.plot = 1)
```



# give id to each location

```{r}
data <- data %>% 
  mutate(land_id_full = paste0(city_id, land_category, land_id))
```


# Wide to long
```{r}
price_cols = c()
i = 1
for (col in names(data)) {
    if (grepl("price", col, fixed = TRUE)) {
        price_cols <- append(price_cols, col)
        i <- i + 1
    }
}

long <- data %>% 
  gather("price_year", "price", all_of(price_cols)) %>%  # wide to long
  mutate(price = as.numeric(price)) %>% 
  mutate(price_year = str_replace_all(price_year, pattern = "price_", replacement = "")) %>%  # remove prefix of price_year
  filter(price != 0) %>%  # only rows with price
  mutate(price_date = as.POSIXct(paste(price_year, 1, 1, sep = "-")))  # convert year from string to POSIX
```

# create some features

```{r}
# time lapse
long <- long %>%
  mutate(time_lapse = price_date - map_date) %>%  # time lapse days
  mutate(time_lapse_year = ceiling(time_lapse / 365)) %>% 
  mutate(time_lapse_year = replace_na(time_lapse_year, -999))# time lapse years

# is_depth
long <- long %>% 
  mutate(is_depth = !is.na(water_depth_scaled))
```

```{r}
# distribution of price
plot_price <- function(data, x, fill='a') {
    ggplot(data, aes(x = x, y = ..density.., fill = fill)) +
        geom_histogram(position = "identity", alpha = 0.9, bins = 50) +
        geom_density(aes(color = fill, alpha = 0.1), show.legend = F)
}

plot_price(long, long$price)

# log of price
long <- long %>% 
  mutate(price_log = log10(price))

plot_price(long, long$price_log)
plot_price(long, long$price_log, long$is_depth)
```


```{r}
ggplot(long, aes(x = factor(price_year), y = price_log)) +
    geom_boxplot() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(long, aes(x = factor(city_id), y = price_log)) +
    geom_boxplot() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(long, aes(x = factor(time_lapse_year), y = price_log)) +
    geom_boxplot()
```


## Linear Model

```{r}
model_glm <- lm(data = long, formula = price_log ~ factor(time_lapse_year))
summary(model_glm)
```


```{r}
coef_tb <- model_glm %>% 
    tidy(conf.int = TRUE) %>% 
    filter(term != '(Intercept)') %>% 
    mutate(term = gsub(term, pattern = 'factor\\(time_lapse_year\\)', replacement = '')) %>% 
    mutate(term = as.integer(term))
coef_tb

ggplot(data = coef_tb) +
    geom_pointrange(aes(x = term, y = estimate, ymin = conf.low, ymax = conf.high))
```


```{r}
plot(model_glm)
lag.plot(long$price_log)
```



## Linear Mixed Model (Only random intercept)


```{r}
model_lmm <- lmer(data = long, formula = price_log ~ factor(time_lapse_year) + (1 | price_year) + (1 | city_id))
summary(model_lmm)
```


```{r}
coef_tb <- model_lmm %>% 
    tidy(conf.int = TRUE) %>% 
    filter(group == 'fixed') %>%
    filter(term != '(Intercept)') %>%
    mutate(term = gsub(term, pattern = 'factor\\(time_lapse_year\\)', replacement = '')) %>% 
    mutate(term = as.integer(term))
coef_tb

ggplot(data = coef_tb) +
    geom_pointrange(aes(x = term, y = estimate, ymin = conf.low, ymax = conf.high))
```


```{r}
plot(model_glmm)

qqnorm(resid(model_glmm))
qqline(resid(model_glmm))
```

## Linear Mixed Model (random intercept + random coefficitnet)

```{r}
model_lmm_coef <- brm(
  formula = price_log ~ factor(time_lapse_year) + (factor(time_lapse_year) || price_year) + (factor(time_lapse_year) || city_id),
  family = gaussian(link = "identity"),
  data = long,
  seed = 1,
  iter = 6000,
  warmup = 5000,
  control = list(adapt_delta = 0.97, max_treedepth = 15)
)
```

